language: node_js
node_js:
 - 0.10
 - 4.2
sudo: false
before_install:
 - npm install -g npm@3
 - npm --version
 - phantomjs --version
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
addons:
 firefox: "36.0"
